### ISSUE TITLE
#Error with annoy package

### ISSUE THREAD

**Issue by SwethaMK09** [kashishahuja2002/Microsoft-Intern-Engage#2]
I am having error in installing annoy package I am using pycharm platform, what platform did you used and what python version did you use? plz kindly help me with this.
![annoyerror](https://user-images.githubusercontent.com/106295169/172110099-32f6cb27-c30d-466a-bef8-86f45005af22.PNG)

**Comment by kashishahuja2002** [comment]
Hello,
I used the pyCharm platform and Python 3.10.2.
You can find the installation procedure and example in readme file, https://github.com/spotify/annoy.
Kindly go through it. Let me know if the doubt still persists.

**Comment by kashishahuja2002** [comment]
As there is no response from your side, I assume that the issue is resolved. 
Closing the issue.
